Repository knztnt/InvSys, pull requests merged in 2020-08, with the labels that each got.

#22 GUI v2.0
  app/models/profile.model.js
  client/public/android-chrome-192x192.png
  client/public/android-chrome-512x512.png
  client/public/apple-touch-icon.png
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon.ico
  client/src/App.css
  client/src/components/home.component.js
  client/src/components/images/bkgrnd.jpg
  client/src/components/images/component.jpg
  client/src/components/images/landing-img-2.png
  client/src/components/images/landing-img.png
  client/src/components/images/login-img.png
  client/src/components/images/services.jpg
  client/src/components/images/track.jpg
  client/src/components/images/updates.jpg
  client/src/components/item/list-item.component.js
  client/src/components/item/request-item.component.js
  client/src/components/login.component.js
  client/src/components/navbar.component.js
  client/src/navbar-brand-dark.png
  client/src/navbar-brand-light.png
  client/src/navbar-brand-primary.png
  client/src/navbar-logo-blue.png
  client/src/navbar-logo-white.png
  client/src/navbar-new-logo.png
Labels: enhancement, good first issue

#23 API calls unit tests
  client/package-lock.json
  client/package.json
  client/src/App.test.js
  client/src/__mocks__/axios.js
  client/src/services/__test__/auth.service.test.js
  client/src/services/__test__/item.service.test.js
  client/src/setupTests.js
Labels: dependencies, good first issue

#24 Unit Testing | Router & User Input Validation & Component Rendering
  client/package-lock.json
  client/package.json
  client/src/App.test.js
  client/src/components/register.component.js
  client/src/router.test.js
  client/src/setupTestRouter.js
  client/src/setupTests.js
Labels: help wanted

#25 Dashboard v1.0
  client/src/App.css
  client/src/components/dashboard.component.js
  client/src/components/home.component.js
  client/src/components/item/list-item.component.js
  client/src/components/item/view-services.component.js
  client/src/components/navbar.component.js
  client/src/components/sidebar.component.js
Labels: enhancement, good first issue, help wanted
